#site_name: Homelab
#theme: readthedocs
#site_dir: ../docs
#nav:
#        - Home: index.md
#        - Homelab: homelab.md

site_name: Homelab
theme: readthedocs
site_dir: ../docs
nav:
        - Home: index.md
        - Homelab: homelab.md
#theme:
#    name: null
#    custom_dir: 'custom_theme/'
plugins: []
